### ISSUE TITLE
项目启动不起来，一直报这个错g

### ISSUE THREAD

**Issue by lwpgit** [where12138/HIKVISIONServer#4]
Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/jna/examples/win32/W32API$HWND
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.privateGetPublicMethods(Class.java:2902)
        at java.lang.Class.getMethods(Class.java:1615)
        at sun.misc.ProxyGenerator.generateClassFile(ProxyGenerator.java:451)
        at sun.misc.ProxyGenerator.generateProxyClass(ProxyGenerator.java:339)
        at java.lang.reflect.Proxy$ProxyClassFactory.apply(Proxy.java:639)
        at java.lang.reflect.Proxy$ProxyClassFactory.apply(Proxy.java:557)
        at java.lang.reflect.WeakCache$Factory.get(WeakCache.java:230)
        at java.lang.reflect.WeakCache.get(WeakCache.java:127)
        at java.lang.reflect.Proxy.getProxyClass0(Proxy.java:419)
        at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:719)
        at com.sun.jna.Native.loadLibrary(Native.java:396)
        at com.sun.jna.Native.loadLibrary(Native.java:378)
        at com.sht.netDVR.HCNetSDK.<clinit>(HCNetSDK.java:37)
        at sun.misc.Unsafe.ensureClassInitialized(Native Method)

**Comment by aqnxy** [comment]
运行jar包
